env:
  CIRRUS_CLONE_DEPTH: 1

macos_task:
  osx_instance:
    image: catalina-base
  install_script:
    - brew install pkg-config python gnu-sed glib pixman make sdl2 bash ninja
  script:
    - env
    - mkdir build
    - cd build
    - ../configure --python=/usr/local/bin/python3 --enable-werror --target-list=aarch64-softmmu
                   --extra-cflags='-Wno-error=deprecated-declarations'
                   || { cat config.log meson-logs/meson-log.txt; exit 1; }
    - gmake -j$(sysctl -n hw.ncpu)
    - otool -L qemu-system-aarch64
